apiVersion: v1
kind: LimitRange
metadata:
  name: build
  namespace: go-demo-5-build
spec:
  limits:
  - default:
      memory: 500Mi
      cpu: 0.2
    defaultRequest:
      memory: 250Mi
      cpu: 0.1
    max:
      memory: 500Mi
      cpu: 0.5
    min:
      memory: 5Mi
      cpu: 0.005
    type: Container
